### ISSUE TITLE
parsing error in right heading

### ISSUE THREAD

**Issue by caasi** [clkao/billab#4]
![billab-right-heading](https://cloud.githubusercontent.com/assets/1164470/2813728/8f92f17a-ce95-11e3-8aff-88d314d3a752.png)

**Comment by clkao** [comment]
這是有 renumber 的喔，還是你指那邊呢 parse 錯？

**Comment by caasi** [comment]
我懂了，那是我看錯。
有打算 heading 修改了也標上顏色嗎？

**Comment by clkao** [comment]
有道理耶
